'use client';

import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { Button } from '@/components/ui/button';

type Defaults = { buyPricePerKg: number; sellPricePerKg: number; allInCostPerKg: number };
type Audit = { id: string; createdAt: string; payload: Record<string, unknown>; actor?: { fullName: string } };
export default function SettingsPage() {
  const [values, setValues] = useState<Defaults>({ buyPricePerKg: 120, sellPricePerKg: 570, allInCostPerKg: 450 }); const [audit, setAudit] = useState<Audit[]>([]); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  async function load() { try { const [defaults, history] = await Promise.all([api<Defaults>('/admin/economics/defaults'), api<Audit[]>('/admin/economics/audit')]); setValues(defaults); setAudit(history); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load settings'); } } useEffect(() => { load(); }, []);
  async function save() { setSaving(true); setMessage(''); try { await api('/admin/economics/defaults', { method: 'PATCH', body: JSON.stringify(values) }); setMessage('Economics defaults saved.'); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save settings'); } finally { setSaving(false); } }
  return <div className="space-y-6"><div><p className="text-sm text-muted">Configuration</p><h1 className="text-3xl font-heading font-bold text-text">Settings</h1><p className="mt-1 text-sm text-muted">Economics defaults used by collections and sales.</p></div>{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message && <p className="rounded-lg bg-green-50 p-3 text-sm text-green-700">{message}</p>}<div className="grid grid-cols-[1fr_1.4fr] gap-6"><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-heading text-lg font-bold">Economics defaults</h2><div className="mt-5 space-y-4"><label className="block text-sm font-medium">Buy price per kg<input type="number" min="0" step="0.01" value={values.buyPricePerKg} onChange={(e) => setValues({ ...values, buyPricePerKg: Number(e.target.value) })} className="mt-1 w-full rounded-lg border border-gray-200 px-3 py-2.5" /></label><label className="block text-sm font-medium">Sell price per kg<input type="number" min="0" step="0.01" value={values.sellPricePerKg} onChange={(e) => setValues({ ...values, sellPricePerKg: Number(e.target.value) })} className="mt-1 w-full rounded-lg border border-gray-200 px-3 py-2.5" /></label><label className="block text-sm font-medium">All-in cost per kg<input type="number" min="0" step="0.01" value={values.allInCostPerKg} onChange={(e) => setValues({ ...values, allInCostPerKg: Number(e.target.value) })} className="mt-1 w-full rounded-lg border border-gray-200 px-3 py-2.5" /></label><div className="rounded-xl bg-tint p-4"><p className="text-xs text-muted">Current sales margin</p><p className="mt-1 text-xl font-bold text-forest">₦{(values.sellPricePerKg - values.allInCostPerKg).toLocaleString()} / kg</p></div><Button className="w-full" loading={saving} onClick={save}>Save defaults</Button></div></section><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-heading text-lg font-bold">Audit trail</h2><p className="mt-1 text-sm text-muted">Changes to economics defaults.</p><div className="mt-4 divide-y divide-gray-100">{audit.length ? audit.map((entry) => <div key={entry.id} className="py-4"><div className="flex justify-between"><p className="text-sm font-semibold">{entry.actor?.fullName || 'Administrator'}</p><p className="text-xs text-muted">{new Date(entry.createdAt).toLocaleString('en-NG')}</p></div><div className="mt-2 flex flex-wrap gap-2">{Object.entries(entry.payload).map(([key, value]) => <span key={key} className="rounded-full bg-gray-100 px-2.5 py-1 text-xs text-muted">{key}: {String(value)}</span>)}</div></div>) : <p className="py-5 text-sm text-muted">No changes recorded yet.</p>}</div></section></div></div>;
}
